# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_todopago', '0002_operationfailure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationpayment',
            name='payment_date',
            field=models.DateTimeField(verbose_name='payment date'),
        ),
    ]
