# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_todopago', '0003_operationpayment_payment_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationfailure',
            name='answer_key',
            field=models.CharField(default='', max_length=40, verbose_name='answer_key'),
            preserve_default=False,
        ),
    ]
